### ISSUE TITLE
Not working properly with coc-dictionary

### ISSUE THREAD

**Issue by sQVe** [zidhuss/coc-lbdbq#1]
:pray:

I had problems getting this extension to work properly and started debugging. It works find as long as I uninstall `coc-dictionary`. It seems like there's a race condition somewhere.

**Comment by chemzqm** [comment]
I've tested they can work together without problem.

**Comment by sQVe** [comment]
Still not working for me atleast.

**Comment by chemzqm** [comment]
It's fixed on master of coc.nvim, it should use trigger sources only when possible.

**Comment by sQVe** [comment]
Works as expected with https://github.com/neoclide/coc.nvim/commit/8668f301e439dd6349a18d83b6b6cd95687317aa. Closing.
