### ISSUE TITLE
Trigger pattern is ignored

### ISSUE THREAD

**Issue by OkanEsen** [zidhuss/coc-lbdbq#3]
I don't know why but the `triggerPatterns` aren't considered on file type `mail` when I type something. For me, it autocomples on every keystroke instead of doing it only after the keywords specified in `triggerPatterns`.

Any idea why that happens?

![2019-05-21_03-06](https://user-images.githubusercontent.com/552226/58061195-78d31400-7b75-11e9-9c82-6b900ab35d49.png)

<details> 
  <summary>CocInfo </summary>

   ## versions

vim version: NVIM v0.4.0-dev
node +ersion: v10.15.3
coc.nvim version: 0.0.67-8741e930c9
term: xterm-24bit
platform: linux

## Output channel: highlight

[Info  - 2:58:15 AM] Highlight server running in node v10.15.3

</details>

**Comment by chemzqm** [comment]
It's expected, the source need to set `triggerOnly` to `true` to trigger only when trigger pattern match.

**Comment by zidhuss** [comment]
@chemzqm Ok that makes sense. It looks like this property was exposed in https://github.com/neoclide/coc.nvim/commit/b0d60d83944d20d960a13c8e8cc46f727d2d8fa3. This patch is not included in the current `coc.nvim` version `v0.0.67`.

**Comment by chemzqm** [comment]
A new release is available.
